#!/bin/sh

articles='index piod144 piod24 piod48 piod64 piod96 pioda16 piso725 piso730 piso730a piso813 pisop32c32 pisop8r8 pisoda2 piod168 pisoa64 pisoc64 pisop64 pisop32a32 pisops300'

rm doc/html/*

for target in $articles; do
	echo -n "make doc - $target.html... "
	w3m -dump_source w3.p.icpdas.com/reed/pj/ixpio/$target.shtml | sed -n "s/shtml/html/g; w doc/html/$target.html"
	echo 'done'
done
