name: Deploy and Test

on:
  push:
    branches:
      - main  # Cambia la rama si deseas otra

jobs:
  deploy_and_test:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ejecutar script de despliegue
        run:
          echo "Hello world!"
          #echo "Ejecutando script de despliegue..."
