name: Deploy and Test

on:
  push:
    branches:
      - main  # Cambia la rama si deseas otra

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Instalar dependencias
        run: sudo apt-get update && sudo apt-get install -y libsocketcan-dev gcc

      - name: Compilar test.c
        run: gcc -o test test.c -Wall

      - name: Ejecutar test.c
        run: ./test
          

=======
      - name: Ejecutar script de despliegue
        run: |
          echo "Hello world!"
          #echo "Ejecutando script de despliegue..."
>>>>>>> 93f3452064e7cde1b647a396dadadf6b689ce296
